services:
  # ####################################
  # # mysql database  
  # ####################################
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  ##################################
  # Jest on authentication
  ##################################
  authentication-tests:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - mysql
