FROM node:20
# Set the working directory to /usr/src/app
WORKDIR /app
COPY ci/wait-for-it.sh ./
COPY package*.json ./
RUN npm install
COPY . .
COPY ci/test.env ./.env
EXPOSE 3003
RUN chmod +x wait-for-it.sh
CMD ./wait-for-it.sh mysql:3306 -- npm test
