name: BE Node.js Test

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:
  docker-backend-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "auth-server/ci/compose.test.yaml" up --build

    - name: Stop containers
      run: docker-compose -f "auth-server/ci/compose.test.yaml" down
